// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TestApi.Migrations
{
    /// <inheritdoc />
    public partial class Create_Database : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Products",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false),
                    Details_Brand = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Details_Category = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Details_SubCategory = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Details_Manufacturer = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Details_CountryOfOrigin = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Details_Tags = table.Column<List<string>>(type: "json", nullable: false),
                    Pricing_BasePrice = table.Column<decimal>(type: "numeric", nullable: false),
                    Pricing_DiscountedPrice = table.Column<decimal>(type: "numeric", nullable: true),
                    Pricing_Currency = table.Column<string>(type: "text", nullable: false),
                    Pricing_IsOnSale = table.Column<bool>(type: "boolean", nullable: false),
                    Pricing_SaleEndsAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    Inventory_StockQuantity = table.Column<int>(type: "integer", nullable: false),
                    Inventory_Sku = table.Column<string>(type: "text", nullable: false),
                    Inventory_WarehouseLocation = table.Column<string>(type: "text", nullable: true),
                    Inventory_ReorderPoint = table.Column<int>(type: "integer", nullable: false),
                    Specifications_Dimensions = table.Column<Dictionary<string, string>>(type: "json", nullable: false),
                    Specifications_WeightInKg = table.Column<decimal>(type: "numeric", nullable: false),
                    Specifications_Materials = table.Column<List<string>>(type: "json", nullable: false),
                    Specifications_TechnicalSpecs = table.Column<Dictionary<string, string>>(type: "json", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Products", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Products");
        }
    }
}
